version: '3.5'
services:
  backend:
    container_name: backend
    build: ./
    restart: always
    environment:
      MASTER_DB_URL: 'jdbc:postgresql://db-master:5432/social_network'
      MASTER_DB_USER: 'social_network_user'
      MASTER_DB_PASSWORD: 'password'
      SLAVE_DB_URL: 'jdbc:postgresql://db-slave1:5432/social_network'
      SLAVE_DB_USER: 'social_network_user'
      SLAVE_DB_PASSWORD: 'password'
    ports:
      - "8080:8080"

  db-master:
    container_name:  db-master
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'social_network'
      POSTGRES_USER: 'social_network_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/postgres/db-master:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-slave1:
    container_name: db-slave1
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'social_network'
      POSTGRES_USER: 'social_network_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/postgres/db-slave1:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  db-slave2:
    container_name: db-slave2
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'social_network'
      POSTGRES_USER: 'social_network_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/postgres/db-slave2:/var/lib/postgresql/data
    ports:
      - "5434:5432"