version: '3.5'
services:
  backend:
    container_name: backend
    build: ./
    restart: always
    environment:
      MASTER_DB_URL: 'jdbc:postgresql://db-master:5432/social_network'
      MASTER_DB_USER: 'social_network_user'
      MASTER_DB_PASSWORD: 'password'
      SLAVE_DB_URL: 'jdbc:postgresql://db-slave1:5432/social_network'
      SLAVE_DB_USER: 'social_network_user'
      SLAVE_DB_PASSWORD: 'password'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: 'password'
      KAFKA_BOOTSTRAP_SERVERS: 'hl-kafka:9092'
      KAFKA_CONSUMER_GROUP_ID: 'social_network'
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: 'earliest'
      KAFKA_TEMPLATE_DEFAULT_TOPIC: 'posts'
    ports:
      - "8080:8080"

  db-master:
    container_name: db-master
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'social_network'
      POSTGRES_USER: 'social_network_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/postgres/db-master:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-slave1:
    container_name: db-slave1
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'social_network'
      POSTGRES_USER: 'social_network_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/postgres/db-slave1:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  db-slave2:
    container_name: db-slave2
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'social_network'
      POSTGRES_USER: 'social_network_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/postgres/db-slave2:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    container_name: redis
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: 'password'
    ports:
      - "6379:6379"

  hl-kafka:
    container_name: hl-kafka
    image: wurstmeister/kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: hl-zookeeper:2181
      KAFKA_CREATE_TOPICS: "posts:1:1"
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hl-zookeeper:
    container_name: hl-zookeeper
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"