version: '3.5'
services:
  backend:
    container_name: backend
    build: ./
    restart: always
    environment:
      DB_URL: 'jdbc:postgresql://db:5432/social_network'
      DB_USER: 'social_network_user'
      DB_PASSWORD: 'password'
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'social_network'
      POSTGRES_USER: 'social_network_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - hl-homework-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  hl-homework-db: