version: '3.5'
services:
  backend:
    container_name: backend
    build: ./
    restart: always
    environment:
      MYSQL_URL: 'jdbc:mysql://db:3306/social_network'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'social_network'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - hl-homework-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  hl-homework-db: