spring:
  kafka:
    topic: ${KAFKA_TOPIC:unread_message_counters}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29091}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:counter-service}
      auto-offset-reset: earliest

tarantool:
  host: ${TARANTOOL_HOST:localhost}
  port: ${TARANTOOL_PORT:3301}
  username: ${TARANTOOL_USERNAME:tarantool}
  password: ${TARANTOOL_PASSWORD:password}